envVarGroups:
  - name: progotix-shared
    envVars:
      - key: APP_NAME
        value: ProgotiX
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: DB_URL
        fromDatabase:
          name: progotix-db
          property: connectionString

services:
  - type: web
    name: progotix-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - fromGroup: progotix-shared
      - key: SERVICE_MODE
        value: web

  - type: worker
    name: progotix-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - fromGroup: progotix-shared
      - key: SERVICE_MODE
        value: worker

databases:
  - name: progotix-db
    databaseName: progotix_prod
    user: progotix_user
    plan: free
    postgresMajorVersion: "16"
    ipAllowList: []
