<?php

use App\Http\Controllers\Admin\AdminBinaryTreeController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\DepositManagementController;
use App\Http\Controllers\Admin\DepositProofController;
use App\Http\Controllers\Admin\DocumentManagementController;
use App\Http\Controllers\Admin\InvoiceManagementController;
use App\Http\Controllers\Admin\MemberCrudController;
use App\Http\Controllers\Admin\MemberManagementController;
use App\Http\Controllers\Admin\OrderManagementController;
use App\Http\Controllers\Admin\PaymentMethodManagementController;
use App\Http\Controllers\Admin\PayoutExportController;
use App\Http\Controllers\Admin\PlanManagementController;
use App\Http\Controllers\Admin\ProductManagementController;
use App\Http\Controllers\Admin\RankManagementController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\WithdrawalManagementController;
use App\Http\Controllers\BinaryTreeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DownlineMemberController;
use App\Http\Controllers\EarningsController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\InvoicePdfController;
use App\Http\Controllers\NetworkController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\RankController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\WalletController;
use App\Http\Controllers\WithdrawalController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome')->name('home');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('network', NetworkController::class)->name('mlm.network');
    Route::post('network/downlines', [DownlineMemberController::class, 'store'])->name('mlm.network.downlines.store');
    Route::get('binary-tree', BinaryTreeController::class)->name('mlm.binary-tree');
    Route::get('earnings', EarningsController::class)->name('mlm.earnings');
    Route::get('plans', [PlanController::class, 'index'])->name('mlm.plans.index');
    Route::post('plans/{plan}/subscribe', [PlanController::class, 'store'])->name('mlm.plans.subscribe');
    Route::get('shop', ShopController::class)->name('mlm.shop');
    Route::post('shop/{product}/order', [OrderController::class, 'store'])->name('mlm.orders.store');
    Route::get('orders', [OrderController::class, 'index'])->name('mlm.orders');
    Route::get('wallet', [WalletController::class, 'index'])->name('mlm.wallet');
    Route::post('wallet/transfer', [WalletController::class, 'transfer'])->name('mlm.wallet.transfer');
    Route::get('payments', [PaymentController::class, 'index'])->name('mlm.payments.index');
    Route::post('payments/deposits', [PaymentController::class, 'store'])->name('mlm.payments.store');
    Route::get('ranks', RankController::class)->name('mlm.ranks');
    Route::get('documents', [DocumentController::class, 'index'])->name('mlm.documents');
    Route::post('documents', [DocumentController::class, 'store'])->name('mlm.documents.store');
    Route::get('withdrawals', [WithdrawalController::class, 'index'])->name('mlm.withdrawals.index');
    Route::post('withdrawals', [WithdrawalController::class, 'store'])->name('mlm.withdrawals.store');
    Route::get('invoices', InvoiceController::class)->name('mlm.invoices');
    Route::get('invoices/{invoice}/pdf', InvoicePdfController::class)->name('mlm.invoices.pdf');
});

Route::middleware(['auth', 'verified', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', AdminDashboardController::class)->name('dashboard');
    Route::get('members', MemberManagementController::class)->name('members');
    Route::patch('members/{user}', [MemberCrudController::class, 'update'])->name('members.update');
    Route::delete('members/{user}', [MemberCrudController::class, 'destroy'])->name('members.destroy');
    Route::get('products', [ProductManagementController::class, 'index'])->name('products');
    Route::post('products', [ProductManagementController::class, 'store'])->name('products.store');
    Route::patch('products/{product}', [ProductManagementController::class, 'update'])->name('products.update');
    Route::delete('products/{product}', [ProductManagementController::class, 'destroy'])->name('products.destroy');
    Route::get('payment-methods', [PaymentMethodManagementController::class, 'index'])->name('payment-methods');
    Route::post('payment-methods', [PaymentMethodManagementController::class, 'store'])->name('payment-methods.store');
    Route::patch('payment-methods/{paymentMethod}', [PaymentMethodManagementController::class, 'update'])->name('payment-methods.update');
    Route::delete('payment-methods/{paymentMethod}', [PaymentMethodManagementController::class, 'destroy'])->name('payment-methods.destroy');
    Route::get('deposits', [DepositManagementController::class, 'index'])->name('deposits');
    Route::patch('deposits/{depositRequest}', [DepositManagementController::class, 'update'])->name('deposits.update');
    Route::get('deposits/{depositRequest}/proof', DepositProofController::class)->name('deposits.proof');
    Route::get('orders', [OrderManagementController::class, 'index'])->name('orders');
    Route::patch('orders/{order}', [OrderManagementController::class, 'update'])->name('orders.update');
    Route::get('binary-tree/{user?}', AdminBinaryTreeController::class)->name('binary-tree');
    Route::get('plans', [PlanManagementController::class, 'index'])->name('plans');
    Route::post('plans', [PlanManagementController::class, 'store'])->name('plans.store');
    Route::patch('plans/{plan}', [PlanManagementController::class, 'update'])->name('plans.update');
    Route::delete('plans/{plan}', [PlanManagementController::class, 'destroy'])->name('plans.destroy');
    Route::get('withdrawals', [WithdrawalManagementController::class, 'index'])->name('withdrawals');
    Route::patch('withdrawals/{withdrawalRequest}', [WithdrawalManagementController::class, 'update'])->name('withdrawals.update');
    Route::get('withdrawals-export', PayoutExportController::class)->name('withdrawals.export');
    Route::get('invoices', InvoiceManagementController::class)->name('invoices');
    Route::get('ranks', [RankManagementController::class, 'index'])->name('ranks');
    Route::post('ranks', [RankManagementController::class, 'store'])->name('ranks.store');
    Route::patch('ranks/{rank}', [RankManagementController::class, 'update'])->name('ranks.update');
    Route::delete('ranks/{rank}', [RankManagementController::class, 'destroy'])->name('ranks.destroy');
    Route::get('documents', [DocumentManagementController::class, 'index'])->name('documents');
    Route::patch('documents/{document}', [DocumentManagementController::class, 'update'])->name('documents.update');
    Route::get('commission-rules', \App\Livewire\Admin\CommissionRules::class)->name('commission-rules');
    Route::view('refunds', 'admin.refunds')->name('refunds');
    Route::get('reports', ReportController::class)->name('reports');

});

require __DIR__.'/settings.php';
