<?php

return [
    'list' => [
        ['code' => 'AR', 'name' => 'Argentina', 'dial_code' => '+54'],
        ['code' => 'AU', 'name' => 'Australia', 'dial_code' => '+61'],
        ['code' => 'AT', 'name' => 'Austria', 'dial_code' => '+43'],
        ['code' => 'BH', 'name' => 'Bahrain', 'dial_code' => '+973'],
        ['code' => 'BD', 'name' => 'Bangladesh', 'dial_code' => '+880'],
        ['code' => 'BE', 'name' => 'Belgium', 'dial_code' => '+32'],
        ['code' => 'BR', 'name' => 'Brazil', 'dial_code' => '+55'],
        ['code' => 'BN', 'name' => 'Brunei', 'dial_code' => '+673'],
        ['code' => 'BG', 'name' => 'Bulgaria', 'dial_code' => '+359'],
        ['code' => 'KH', 'name' => 'Cambodia', 'dial_code' => '+855'],
        ['code' => 'CM', 'name' => 'Cameroon', 'dial_code' => '+237'],
        ['code' => 'CA', 'name' => 'Canada', 'dial_code' => '+1'],
        ['code' => 'CL', 'name' => 'Chile', 'dial_code' => '+56'],
        ['code' => 'CN', 'name' => 'China', 'dial_code' => '+86'],
        ['code' => 'CO', 'name' => 'Colombia', 'dial_code' => '+57'],
        ['code' => 'HR', 'name' => 'Croatia', 'dial_code' => '+385'],
        ['code' => 'CY', 'name' => 'Cyprus', 'dial_code' => '+357'],
        ['code' => 'CZ', 'name' => 'Czech Republic', 'dial_code' => '+420'],
        ['code' => 'DK', 'name' => 'Denmark', 'dial_code' => '+45'],
        ['code' => 'EG', 'name' => 'Egypt', 'dial_code' => '+20'],
        ['code' => 'EE', 'name' => 'Estonia', 'dial_code' => '+372'],
        ['code' => 'FI', 'name' => 'Finland', 'dial_code' => '+358'],
        ['code' => 'FR', 'name' => 'France', 'dial_code' => '+33'],
        ['code' => 'DE', 'name' => 'Germany', 'dial_code' => '+49'],
        ['code' => 'GH', 'name' => 'Ghana', 'dial_code' => '+233'],
        ['code' => 'GR', 'name' => 'Greece', 'dial_code' => '+30'],
        ['code' => 'HK', 'name' => 'Hong Kong', 'dial_code' => '+852'],
        ['code' => 'HU', 'name' => 'Hungary', 'dial_code' => '+36'],
        ['code' => 'IS', 'name' => 'Iceland', 'dial_code' => '+354'],
        ['code' => 'IN', 'name' => 'India', 'dial_code' => '+91'],
        ['code' => 'ID', 'name' => 'Indonesia', 'dial_code' => '+62'],
        ['code' => 'IE', 'name' => 'Ireland', 'dial_code' => '+353'],
        ['code' => 'IL', 'name' => 'Israel', 'dial_code' => '+972'],
        ['code' => 'IT', 'name' => 'Italy', 'dial_code' => '+39'],
        ['code' => 'JP', 'name' => 'Japan', 'dial_code' => '+81'],
        ['code' => 'JO', 'name' => 'Jordan', 'dial_code' => '+962'],
        ['code' => 'KE', 'name' => 'Kenya', 'dial_code' => '+254'],
        ['code' => 'KW', 'name' => 'Kuwait', 'dial_code' => '+965'],
        ['code' => 'LV', 'name' => 'Latvia', 'dial_code' => '+371'],
        ['code' => 'LB', 'name' => 'Lebanon', 'dial_code' => '+961'],
        ['code' => 'LT', 'name' => 'Lithuania', 'dial_code' => '+370'],
        ['code' => 'LU', 'name' => 'Luxembourg', 'dial_code' => '+352'],
        ['code' => 'MO', 'name' => 'Macau', 'dial_code' => '+853'],
        ['code' => 'MY', 'name' => 'Malaysia', 'dial_code' => '+60'],
        ['code' => 'MV', 'name' => 'Maldives', 'dial_code' => '+960'],
        ['code' => 'MT', 'name' => 'Malta', 'dial_code' => '+356'],
        ['code' => 'MU', 'name' => 'Mauritius', 'dial_code' => '+230'],
        ['code' => 'MX', 'name' => 'Mexico', 'dial_code' => '+52'],
        ['code' => 'MA', 'name' => 'Morocco', 'dial_code' => '+212'],
        ['code' => 'NP', 'name' => 'Nepal', 'dial_code' => '+977'],
        ['code' => 'NL', 'name' => 'Netherlands', 'dial_code' => '+31'],
        ['code' => 'NZ', 'name' => 'New Zealand', 'dial_code' => '+64'],
        ['code' => 'NG', 'name' => 'Nigeria', 'dial_code' => '+234'],
        ['code' => 'NO', 'name' => 'Norway', 'dial_code' => '+47'],
        ['code' => 'OM', 'name' => 'Oman', 'dial_code' => '+968'],
        ['code' => 'PK', 'name' => 'Pakistan', 'dial_code' => '+92'],
        ['code' => 'PA', 'name' => 'Panama', 'dial_code' => '+507'],
        ['code' => 'PE', 'name' => 'Peru', 'dial_code' => '+51'],
        ['code' => 'PH', 'name' => 'Philippines', 'dial_code' => '+63'],
        ['code' => 'PL', 'name' => 'Poland', 'dial_code' => '+48'],
        ['code' => 'PT', 'name' => 'Portugal', 'dial_code' => '+351'],
        ['code' => 'QA', 'name' => 'Qatar', 'dial_code' => '+974'],
        ['code' => 'RO', 'name' => 'Romania', 'dial_code' => '+40'],
        ['code' => 'RU', 'name' => 'Russia', 'dial_code' => '+7'],
        ['code' => 'SA', 'name' => 'Saudi Arabia', 'dial_code' => '+966'],
        ['code' => 'SG', 'name' => 'Singapore', 'dial_code' => '+65'],
        ['code' => 'ZA', 'name' => 'South Africa', 'dial_code' => '+27'],
        ['code' => 'KR', 'name' => 'South Korea', 'dial_code' => '+82'],
        ['code' => 'ES', 'name' => 'Spain', 'dial_code' => '+34'],
        ['code' => 'LK', 'name' => 'Sri Lanka', 'dial_code' => '+94'],
        ['code' => 'SE', 'name' => 'Sweden', 'dial_code' => '+46'],
        ['code' => 'CH', 'name' => 'Switzerland', 'dial_code' => '+41'],
        ['code' => 'TW', 'name' => 'Taiwan', 'dial_code' => '+886'],
        ['code' => 'TZ', 'name' => 'Tanzania', 'dial_code' => '+255'],
        ['code' => 'TH', 'name' => 'Thailand', 'dial_code' => '+66'],
        ['code' => 'TR', 'name' => 'Turkey', 'dial_code' => '+90'],
        ['code' => 'UG', 'name' => 'Uganda', 'dial_code' => '+256'],
        ['code' => 'UA', 'name' => 'Ukraine', 'dial_code' => '+380'],
        ['code' => 'AE', 'name' => 'United Arab Emirates', 'dial_code' => '+971'],
        ['code' => 'GB', 'name' => 'United Kingdom', 'dial_code' => '+44'],
        ['code' => 'US', 'name' => 'United States', 'dial_code' => '+1'],
        ['code' => 'UZ', 'name' => 'Uzbekistan', 'dial_code' => '+998'],
        ['code' => 'VN', 'name' => 'Vietnam', 'dial_code' => '+84'],
        ['code' => 'ZM', 'name' => 'Zambia', 'dial_code' => '+260'],
    ],
];
