<?php

return [
    'brand' => [
        'name' => 'ProgotiX',
        'tagline' => 'MLM Command Center',
        'description' => 'Referral growth, commissions, payouts, and binary operations in one operating surface.',
    ],

    'strategy' => [
        'recommended_model' => 'Retail-first hybrid MLM with e-commerce orders, direct sponsor bonus, capped level bonus, and binary team visibility.',
        'avoid' => [
            'Fixed daily ROI or guaranteed investment return plans',
            'Commissions triggered mainly by joining fees or package buying without genuine retail demand',
            'Downline payout promises that depend on continuous new investor inflow',
        ],
        'principles' => [
            'Commissions should come from paid retail orders and verified customer demand',
            'Recruitment may support team growth, but payout eligibility should not depend mainly on recruitment',
            'Refunds, cancellations, and clawbacks should reduce commissionable volume',
            'Income claims should be based on real participant outcomes, not hype or guarantees',
        ],
    ],

    'wallet' => [
        'currency' => 'USD',
        'supported_currencies' => [
            ['code' => 'USD', 'label' => 'US Dollar', 'rate' => 1],
            ['code' => 'BDT', 'label' => 'Bangladeshi Taka', 'rate' => 117.5],
            ['code' => 'EUR', 'label' => 'Euro', 'rate' => 0.92],
            ['code' => 'AED', 'label' => 'UAE Dirham', 'rate' => 3.67],
        ],
        'transfer_fee_rate' => 0.02,
        'payout_methods' => [
            'Bank Transfer',
            'E-Wallet',
            'Crypto Wallet',
            'Binance Pay (manual review)',
        ],
    ],

    'commission' => [
        'subscription' => [
            'level_distribution' => [
                1 => 0.50,
                2 => 0.15,
                3 => 0.10,
                4 => 0.07,
                5 => 0.05,
                6 => 0.04,
                7 => 0.03,
                8 => 0.02,
                9 => 0.02,
                10 => 0.02,
            ],
        ],
        'retail' => [
            'team_distribution' => [
                1 => 1.00,
            ],
        ],
    ],

    'commerce' => [
        'categories' => [
            ['key' => 'wellness', 'label' => 'Wellness'],
            ['key' => 'beauty', 'label' => 'Beauty'],
            ['key' => 'home', 'label' => 'Home Care'],
            ['key' => 'nutrition', 'label' => 'Nutrition'],
        ],
        'products' => [
            [
                'sku' => 'PGX-WEL-100',
                'name' => 'Daily Vitality Pack',
                'category' => 'wellness',
                'price' => 1490,
                'bv' => 220,
                'retail_commission_rate' => 0.10,
                'team_volume' => 220,
                'description' => 'Starter retail bundle designed for repeat monthly orders.',
            ],
            [
                'sku' => 'PGX-BEA-210',
                'name' => 'Glow Skin Ritual Set',
                'category' => 'beauty',
                'price' => 1890,
                'bv' => 280,
                'retail_commission_rate' => 0.12,
                'team_volume' => 280,
                'description' => 'Mid-ticket beauty line for social selling and product demos.',
            ],
            [
                'sku' => 'PGX-HOM-315',
                'name' => 'Smart Home Essentials Kit',
                'category' => 'home',
                'price' => 2390,
                'bv' => 340,
                'retail_commission_rate' => 0.11,
                'team_volume' => 340,
                'description' => 'Family-use recurring consumption product for stable retail volume.',
            ],
            [
                'sku' => 'PGX-NUT-420',
                'name' => 'Performance Nutrition Stack',
                'category' => 'nutrition',
                'price' => 3290,
                'bv' => 520,
                'retail_commission_rate' => 0.15,
                'team_volume' => 520,
                'description' => 'Higher-value product line for premium customer baskets.',
            ],
        ],
        'rules' => [
            'Retail commission should post only after payment confirmation.',
            'Binary or team bonus should use verified order volume, not simple signup count.',
            'Refunded orders should reverse pending commissions automatically.',
        ],
    ],

    'navigation' => [
        'member' => [
            [
                'label' => 'Dashboard',
                'short_label' => 'Dashboard',
                'icon' => 'home',
                'route' => 'dashboard',
                'pattern' => 'dashboard',
                'description' => 'Daily operating cockpit for wallet, growth, activity, and next actions.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Referral Network',
                'short_label' => 'Network',
                'icon' => 'user-group',
                'route' => 'mlm.network',
                'pattern' => 'mlm.network',
                'description' => 'Direct and second-level member visibility with sponsor context.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Packages',
                'short_label' => 'Packages',
                'icon' => 'cube',
                'route' => 'mlm.plans.index',
                'pattern' => 'mlm.plans.*',
                'description' => 'Activation catalog for subscription packs and qualification levels.',
            ],
            [
                'label' => 'Shop',
                'short_label' => 'Shop',
                'icon' => 'shopping-bag',
                'route' => 'mlm.shop',
                'pattern' => 'mlm.shop',
                'description' => 'Retail-first commerce surface for products, order value, and commissionable volume.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Orders',
                'short_label' => 'Orders',
                'icon' => 'shopping-cart',
                'route' => 'mlm.orders',
                'pattern' => 'mlm.orders*',
                'description' => 'Retail order history, basket totals, and commission-ready order records.',
            ],
            [
                'label' => 'Earnings',
                'short_label' => 'Earnings',
                'icon' => 'banknotes',
                'route' => 'mlm.earnings',
                'pattern' => 'mlm.earnings',
                'description' => 'Ledger of direct, level, binary, and future retail commissions.',
            ],
            [
                'label' => 'Binary Tree',
                'short_label' => 'Tree',
                'icon' => 'squares-2x2',
                'route' => 'mlm.binary-tree',
                'pattern' => 'mlm.binary-tree',
                'description' => 'Placement and carry-forward visibility for team volume management.',
            ],
            [
                'label' => 'Payments',
                'short_label' => 'Payments',
                'icon' => 'credit-card',
                'route' => 'mlm.payments.index',
                'pattern' => 'mlm.payments*',
                'description' => 'Country-aware deposit desk for e-wallet, bank, card, and crypto channels.',
            ],
            [
                'label' => 'Withdrawals',
                'short_label' => 'Withdrawals',
                'icon' => 'arrows-right-left',
                'route' => 'mlm.withdrawals.index',
                'pattern' => 'mlm.withdrawals.*',
                'description' => 'Payout request flow with wallet deduction and approval lifecycle.',
            ],
            [
                'label' => 'Wallet',
                'short_label' => 'Wallet',
                'icon' => 'wallet',
                'route' => 'mlm.wallet',
                'pattern' => 'mlm.wallet*',
                'description' => 'Balance, transfer fee, internal transfer, and multi-currency wallet view.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Invoices',
                'short_label' => 'Invoices',
                'icon' => 'document-text',
                'route' => 'mlm.invoices',
                'pattern' => 'mlm.invoices',
                'description' => 'Billing history and printable records for package and future order transactions.',
            ],
            [
                'label' => 'Rank & Rewards',
                'short_label' => 'Rank',
                'icon' => 'trophy',
                'route' => 'mlm.ranks',
                'pattern' => 'mlm.ranks',
                'description' => 'Performance rank ladder, upgrade tracking, and reward milestones.',
            ],
            [
                'label' => 'Documents',
                'short_label' => 'Docs',
                'icon' => 'folder-open',
                'route' => 'mlm.documents',
                'pattern' => 'mlm.documents*',
                'description' => 'Optional KYC or identity file submission and approval status.',
            ],
            [
                'label' => 'Profile',
                'short_label' => 'Profile',
                'icon' => 'identification',
                'route' => 'profile.edit',
                'pattern' => 'profile.edit',
                'description' => 'Professional member identity, contact details, country, and referral profile settings.',
                'mobile_primary' => true,
            ],
        ],
        'admin' => [
            [
                'label' => 'Admin Dashboard',
                'short_label' => 'Admin',
                'icon' => 'shield-check',
                'route' => 'admin.dashboard',
                'pattern' => 'admin.dashboard',
                'description' => 'Executive overview of members, payouts, sales, and growth health.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Members',
                'short_label' => 'Members',
                'icon' => 'users',
                'route' => 'admin.members',
                'pattern' => 'admin.members*',
                'description' => 'Directory, status control, and member lifecycle management.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Product Catalog',
                'short_label' => 'Catalog',
                'icon' => 'shopping-bag',
                'route' => 'admin.products',
                'pattern' => 'admin.products*',
                'description' => 'Commerce catalog, pricing, BV, and retail commission settings.',
            ],
            [
                'label' => 'Order Operations',
                'short_label' => 'Orders',
                'icon' => 'shopping-cart',
                'route' => 'admin.orders',
                'pattern' => 'admin.orders*',
                'description' => 'Retail order monitoring, status control, and commissionable volume review.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Plan Management',
                'short_label' => 'Plans',
                'icon' => 'cube',
                'route' => 'admin.plans',
                'pattern' => 'admin.plans*',
                'description' => 'Package catalog, price, bonus structure, and qualification control.',
            ],
            [
                'label' => 'Tree Manager',
                'short_label' => 'Tree',
                'icon' => 'squares-plus',
                'route' => 'admin.binary-tree',
                'pattern' => 'admin.binary-tree',
                'description' => 'Operational oversight for team placement and binary structure.',
            ],
            [
                'label' => 'Payment Methods',
                'short_label' => 'Methods',
                'icon' => 'wallet',
                'route' => 'admin.payment-methods',
                'pattern' => 'admin.payment-methods*',
                'description' => 'Configure country-wise e-wallet, bank, card, and crypto methods.',
            ],
            [
                'label' => 'Deposit Queue',
                'short_label' => 'Deposits',
                'icon' => 'arrow-down-circle',
                'route' => 'admin.deposits',
                'pattern' => 'admin.deposits*',
                'description' => 'Approve, reject, and audit incoming deposit funding requests.',
            ],
            [
                'label' => 'Withdrawal Queue',
                'short_label' => 'Payouts',
                'icon' => 'credit-card',
                'route' => 'admin.withdrawals',
                'pattern' => 'admin.withdrawals*',
                'description' => 'Approve, reject, export, and audit payout requests.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Invoices',
                'short_label' => 'Invoices',
                'icon' => 'document-duplicate',
                'route' => 'admin.invoices',
                'pattern' => 'admin.invoices',
                'description' => 'Billing operations across package activations and future retail orders.',
            ],
            [
                'label' => 'Rank Engine',
                'short_label' => 'Ranks',
                'icon' => 'trophy',
                'route' => 'admin.ranks',
                'pattern' => 'admin.ranks*',
                'description' => 'Achievement ladder, qualification thresholds, and reward settings.',
            ],
            [
                'label' => 'Documents & KYC',
                'short_label' => 'Docs',
                'icon' => 'folder-open',
                'route' => 'admin.documents',
                'pattern' => 'admin.documents*',
                'description' => 'Review optional identity documents and maintain verification workflow.',
            ],
            [
                'label' => 'Reports',
                'short_label' => 'Reports',
                'icon' => 'presentation-chart-line',
                'route' => 'admin.reports',
                'pattern' => 'admin.reports',
                'description' => 'Performance analytics for payout mix, activation trend, and business health.',
                'mobile_primary' => true,
            ],
            [
                'label' => 'Commission Rules',
                'short_label' => 'Rules',
                'icon' => 'scale',
                'route' => 'admin.commission-rules',
                'pattern' => 'admin.commission-rules',
                'description' => 'Edit commission rates, levels, binary matching, and refund policies.',
            ],
            [
                'label' => 'Refunds',
                'short_label' => 'Refunds',
                'icon' => 'arrow-up-circle',
                'route' => 'admin.refunds',
                'pattern' => 'admin.refunds*',
                'description' => 'Manage refund requests, commission reversals, and clawbacks.',
            ],
        ],
    ],
    'refund_policy' => 'Full refund within 7 days for unshipped orders. Commissions auto-reversed. Contact support for exceptions.',
];

